### ISSUE TITLE
如果要在编译添加docker的话怎么添加呢

### ISSUE THREAD

**Issue by hulisang** [Cipher2020/peterx0323#1]
如题，在config里面只找到了luci-app-dockerman没有docker，是不是要添加自定义软件源和luci-app-docker和dockerd

**Comment by Cipher2020** [comment]
config里面最后一行把#去掉就行，就是你提到的这个luci-app-dockerman，我添加的仓库有这个插件。我还不太会玩docker，所以后面被我注释了

**Comment by Cipher2020** [comment]
有些插件还是去掉吧 samba4，zerotier好像会编译失败，所以我复制了很多个.configxxxx，就是为了测试编译失败的插件。

**Comment by hulisang** [comment]
有的时候提示out of disk是不是就是编译失败

**Comment by Cipher2020** [comment]
> 有的时候提示out of disk是不是就是编译失败

  是的 我也碰到这种情况，应该是有些插件编译不了，所以会失败，但是目前我还不是很确定是哪些插件的问题
